### ISSUE TITLE
init and createSoapRequest methods do not return immediately when sth is resolved or rejected

### ISSUE THREAD

**Issue by pablo-ernesto** [mpay24/mpay24-node#7]
In my opinion, the init and createSoapRequest methods must immediately return whenever a resolve or reject is done. At the moment, the statements after a resolve/reject are executed, although it should not do so. Another approach would be to use "else" so that the intended logic is exactly executed.
For instance, the code for createSoapRequest could be so implemented:

```js
createSoapRequest(method, data = {}) {
    return new Promise((resolve, reject) => {
      data.merchantID = mpay24.username;
      mpay24.client[method](data, (err, res) => {
        if (!err) {
          if (res.status === 'OK') {
            resolve(res);
          }
          else reject(res);
        }
        else reject(err);
      });
    });
  }
```

```js
createSoapRequest(method, data = {}) {
    return new Promise((resolve, reject) => {
      data.merchantID = mpay24.username;
      mpay24.client[method](data, (err, res) => {
        if (!err) {
          if (res.status === 'OK') {
            resolve(res);
            return;
          }
          reject(res);
          return;
        }
        reject(err);
        return;
      });
    });
 }
```

**Comment by tobiaslins** [comment]
Thank you!

**Comment by pablo-ernesto** [comment]
Thanks for the immediate bugfix, however this must be fixed also in the init method, too.

`init(username, password, environment = 'LIVE') {
    return new Promise((resolve, reject) => {
      if (!username || !password) {
        reject('Please provide your SOAP user and password')
        return;
      }
      const ep = '/app/bin/etpproxy_v15'
      let mpayEndpoint
      switch (environment) {
        case 'TEST':
          mpayEndpoint = `https://test.mpay24.com${ep}`
          break
        case 'LIVE':
          mpayEndpoint = `https://www.mpay24.com${ep}`
          break
        default:
          mpayEndpoint = `${environment}${ep}`
          break
      }
      const options = {
        endpoint: mpayEndpoint
      }
      soap.createClient(mpay24.wsdl, options, (err, client) => {
        if (!err) {
          client.addHttpHeader('User-Agent', `mpay24-node/${pkg.version}`)
          client.setSecurity(
            new soap.BasicAuthSecurity(`u${username}`, password)
          )
          mpay24.client = client
          mpay24.username = username
          resolve()
        }
        else {
            reject(err)
        }
      })
    })
  }`

**Comment by tobiaslins** [comment]
@pablo-ernesto done!
