### ISSUE TITLE
Cannot parse response

### ISSUE THREAD

**Issue by renehauck** [mpay24/mpay24-node#8]
We currently have a problem with our (online) server. The "selectPayment" function always throws an error. This error is only thrown online (ec2), but it does not occur locally.

> Error: Cannot parse response
>     at finish (/var/app/current/node_modules/soap/lib/client.js:393:19)
>     at parseSync (/var/app/current/node_modules/soap/lib/client.js:381:12)
>     at /var/app/current/node_modules/soap/lib/client.js:357:14
>     at Request._callback (/var/app/current/node_modules/soap/lib/http.js:117:5)
>     at Request.self.callback (/var/app/current/node_modules/request/request.js:186:22)
>     at emitTwo (events.js:106:13)
>     at Request.emit (events.js:191:7)
>     at Request.<anonymous> (/var/app/current/node_modules/request/request.js:1163:10)
>     at emitOne (events.js:96:13)
>     at Request.emit (events.js:188:7)
>     at IncomingMessage.<anonymous> (/var/app/current/node_modules/request/request.js:1085:12)
>     at IncomingMessage.g (events.js:292:16)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by tobiaslins** [comment]
Hey rene!
I think you get this error because of wrong credentials! 
Are you using the same as on your local machine? 
Are you sure that they are set?

I just tested with invalid credentials and I'm getting the same error.

I'll try to implement a better error handling for that issue!

**Comment by renehauck** [comment]
You were right :+1: , thank you for it, but a 401 error code would be better. :smiley:

**Comment by tobiaslins** [comment]
@renehauck definitly!
Hope that we change this soon!

**Comment by tobiaslins** [comment]
Hey @lukasborawski 

Are you using ‘dotenv‘? If yes are you sure that the env variables are already set within createPaymentSession?

Second: How did you check the credentials? Sure that they are working?

If both are not the case I‘m going to look deeper into this issue!

**Comment by lukasborawski** [comment]
No, not using dotenv, just regular way, works fine everywhere. Even when I hardcode the credentials effect is similar. User id and password was used to login to the panel on mPay24 website, so asume that they are correct. @tobiaslins

**Comment by tobiaslins** [comment]
@lukasborawski 
Ah now I see the problem.
You should have a different password for `SOAP` the username stays the same.
If you don't have a Testsystem soap password, please contact our support team to get one! support@mpay24.com

**Comment by lukasborawski** [comment]
Don't know that, so will contact with support. Much thx for help. At least for now :)

**Comment by lukasborawski** [comment]
@tobiaslins after i get the proper pass and login to test I'm trying to handle payment and got this error:

Token from response:
`4+Kd8kzwmD5nnF21PJTu+zUrbd+fL2r8Qqj6/IQQ9Xs=`

Token used with payment request:
```
paymentsApi.acceptPayment({
  tid: '12345',
  pType: 'TOKEN',
  payment: {
    amount: 100,
    currency: 'EUR',
    token: result.token
  }
})
```
and:
`{ status: 'ERROR', returnCode: 'TOKEN_NOT_FOUND', errNo: 30 }`
