### ISSUE TITLE
TOKEN NOT FOUND error

### ISSUE THREAD

**Issue by lukasborawski** [mpay24/mpay24-node#9]
@tobiaslins after i get the proper pass and login to test I'm trying to handle payment and got this error:

Token from response:
`4+Kd8kzwmD5nnF21PJTu+zUrbd+fL2r8Qqj6/IQQ9Xs=`

Token used with payment request:
```
paymentsApi.acceptPayment({
  tid: '12345',
  pType: 'TOKEN',
  payment: {
    amount: 100,
    currency: 'EUR',
    token: result.token
  }
})
```
and:
`{ status: 'ERROR', returnCode: 'TOKEN_NOT_FOUND', errNo: 30 }`

**Comment by tobiaslins** [comment]
Hi @lukasborawski !

Be sure to use the token only once. 
If you have already used it within a `acceptPayment` request, it will return `TOKEN_NOT_FOUND`

**Comment by lukasborawski** [comment]
@tobiaslins what to do with this one?

![zrzut ekranu 2018-03-27 o 12 53 38](https://user-images.githubusercontent.com/1003999/37963237-f8ec79ea-31bd-11e8-8268-4d80bcfc00c9.png)

Redirecting and there is now button, response etc.

**Comment by tobiaslins** [comment]
@lukasborawski 

Everything is correct, just do NOT trigger the acceptPayment call before filling out the creditcard data!

1. createPaymentToken
2. User Input in form
3. acceptPayment

You can read our "Getting started" guide for seamless payments here:
https://docs.mpay24.com/docs/get-started

It is described with the node-sdk
